import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { PATH_SPLITTER, elegantRouterConfig } from './config';
import { buildRouteTrees, createPageFile } from './from-glob';
import { treesToElegantRoutes } from './to-const';
import type { ElegantConstRoute, PageFile } from './types';

const generatedHeader = `/**
 * Generated by \`bun run gen:routes\` from \`${elegantRouterConfig.pageDir}\`.
 * Edit \`src/router/elegant/config.ts\` for names, layouts and meta; do not edit this file.
 */`;

function walkFiles(absDir: string, relativeDir = ''): string[] {
  if (!existsSync(absDir)) return [];

  return readdirSync(absDir, { withFileTypes: true }).flatMap(entry => {
    const relativePath = relativeDir ? `${relativeDir}/${entry.name}` : entry.name;

    if (entry.isDirectory()) {
      if (entry.name === 'components') return [];
      return walkFiles(join(absDir, entry.name), relativePath);
    }

    return entry.isFile() ? [relativePath.replaceAll('\\', PATH_SPLITTER)] : [];
  });
}

export function scanPageFiles(cwd = process.cwd(), pageDir = elegantRouterConfig.pageDir): PageFile[] {
  const globs = walkFiles(resolve(cwd, pageDir)).sort((current, next) => current.localeCompare(next));

  return globs.flatMap(glob => {
    const file = createPageFile(glob, pageDir);
    return file ? [file] : [];
  });
}

export function buildElegantRoutes(files: PageFile[]) {
  return treesToElegantRoutes(buildRouteTrees(files));
}

function serialize(value: unknown, indent = 0): string {
  const pad = '  '.repeat(indent);
  const next = '  '.repeat(indent + 1);

  if (typeof value === 'string') return `'${value.replaceAll("'", "\\'")}'`;
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (value === null) return 'null';

  if (Array.isArray(value)) {
    if (value.every(item => item === null || typeof item !== 'object')) {
      return `[${value.map(item => serialize(item)).join(', ')}]`;
    }

    return `[\n${value.map(item => `${next}${serialize(item, indent + 1)}`).join(',\n')}\n${pad}]`;
  }

  if (typeof value === 'object') {
    const entries = Object.entries(value).filter(([, item]) => item !== undefined);

    if (!entries.length) return '{}';

    const lines = entries.map(([key, item]) => {
      const renderedKey = /^[A-Za-z_$][\w$]*$/.test(key) ? key : `'${key}'`;
      return `${next}${renderedKey}: ${serialize(item, indent + 1)}`;
    });

    return `{\n${lines.join(',\n')}\n${pad}}`;
  }

  return String(value);
}

function renderViewImport(file: PageFile) {
  const key = /^\d/.test(file.routeName) ? `'${file.routeName}'` : file.routeName;
  return `  ${key}: () => import('${file.importPath}')`;
}

function renderLayoutImport(name: string, filePath: string) {
  return `  ${name}: () => import('${toImportPath(filePath)}')`;
}

function toImportPath(relativeFromRoot: string) {
  const posixPath = relativeFromRoot.replaceAll('\\', PATH_SPLITTER);
  const aliasTarget = elegantRouterConfig.alias['@'];
  if (aliasTarget && posixPath.startsWith(`${aliasTarget}${PATH_SPLITTER}`)) {
    return `@${posixPath.slice(aliasTarget.length)}`;
  }
  return posixPath;
}

export function renderImportsFile(files: PageFile[]) {
  const layoutEntries = Object.entries(elegantRouterConfig.layouts)
    .sort(([current], [next]) => current.localeCompare(next))
    .map(([name, filePath]) => renderLayoutImport(name, filePath));
  const viewEntries = [...files]
    .sort((current, next) => current.routeName.localeCompare(next.routeName))
    .map(file => renderViewImport(file));

  return `${generatedHeader}

import type { RouteComponent } from 'vue-router';

export const layouts: Record<string, RouteComponent | (() => Promise<RouteComponent>)> = {
${layoutEntries.join(',\n')}
};

export const views: Record<string, RouteComponent | (() => Promise<RouteComponent>)> = {
${viewEntries.join(',\n')}
};
`;
}

export function renderRoutesFile(routes: ElegantConstRoute[]) {
  return `${generatedHeader}

import type { ElegantConstRoute } from './types';

export const generatedRoutes: ElegantConstRoute[] = ${serialize(routes)};
`;
}

export function generatedFilePaths(cwd = process.cwd()) {
  const dir = resolve(cwd, 'src/router/elegant');

  return {
    dir,
    imports: join(dir, 'imports.ts'),
    routes: join(dir, 'routes.ts')
  };
}

export function buildGeneratedSources(cwd = process.cwd()) {
  const files = scanPageFiles(cwd);
  const routes = buildElegantRoutes(files);

  return {
    files,
    routes,
    imports: renderImportsFile(files),
    routesSource: renderRoutesFile(routes)
  };
}

function writeIfChanged(filePath: string, content: string) {
  const current = existsSync(filePath) ? readFileSync(filePath, 'utf8') : null;
  if (current === content) return false;
  writeFileSync(filePath, content);
  return true;
}

export function writeGeneratedFiles(cwd = process.cwd()) {
  const paths = generatedFilePaths(cwd);
  const sources = buildGeneratedSources(cwd);

  mkdirSync(paths.dir, { recursive: true });

  const changed = [
    writeIfChanged(paths.imports, sources.imports),
    writeIfChanged(paths.routes, sources.routesSource)
  ].some(Boolean);

  return { changed, paths, sources };
}
