/**
 * Generated by `bun run gen:routes` from `src/views`.
 * Edit `src/router/elegant/config.ts` for names, layouts and meta; do not edit this file.
 */

import type { RouteComponent } from 'vue-router';

export const layouts: Record<string, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: () => import('@/layouts/base-layout.vue'),
  blank: () => import('@/layouts/blank-layout.vue')
};

export const views: Record<string, RouteComponent | (() => Promise<RouteComponent>)> = {
  '403': () => import('@/views/_builtin/403/index.vue'),
  '404': () => import('@/views/_builtin/404/index.vue'),
  '500': () => import('@/views/_builtin/500/index.vue'),
  home: () => import('@/views/home/index.vue'),
  login: () => import('@/views/login/index.vue'),
  restricted: () => import('@/views/restricted/index.vue')
};
