/**
 * Generated by `bun run gen:routes` from `src/views`.
 * Edit `src/router/elegant/config.ts` for names, layouts and meta; do not edit this file.
 */

import type { ElegantConstRoute } from './types';

export const generatedRoutes: ElegantConstRoute[] = [
  {
    name: 'forbidden',
    path: '/403',
    meta: {
      title: '无权限',
      i18nKey: 'route.forbidden',
      constant: true,
      hideInMenu: true,
      hideInTab: true
    },
    component: 'layout.blank$view.403'
  },
  {
    name: 'home',
    path: '/home',
    meta: {
      title: '首页',
      i18nKey: 'route.home',
      requiresAuth: true,
      icon: 'home',
      order: 1,
      componentName: 'Home',
      keepAlive: true,
      pinned: true
    },
    component: 'layout.base$view.home'
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url?',
    meta: {
      title: '外链页面',
      i18nKey: 'route.iframe-page',
      requiresAuth: true,
      icon: 'link',
      order: 15,
      componentName: 'IframePage',
      keepAlive: true
    },
    component: 'layout.base$view.iframe-page',
    props: true
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    meta: {
      title: '登录',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true,
      hideInTab: true
    },
    component: 'layout.blank$view.login',
    props: true
  },
  {
    name: 'not-found-page',
    path: '/404',
    meta: {
      title: '页面不存在',
      i18nKey: 'route.notFound',
      constant: true,
      hideInMenu: true,
      hideInTab: true
    },
    component: 'layout.blank$view.404'
  },
  {
    name: 'restricted',
    path: '/restricted',
    meta: {
      title: '受限页',
      i18nKey: 'route.restricted',
      requiresAuth: true,
      icon: 'lock',
      order: 20,
      componentName: 'Restricted',
      keepAlive: true,
      roles: ['R_NOBODY']
    },
    component: 'layout.base$view.restricted'
  },
  {
    name: 'server-error',
    path: '/500',
    meta: {
      title: '服务异常',
      i18nKey: 'route.serverError',
      constant: true,
      hideInMenu: true,
      hideInTab: true
    },
    component: 'layout.blank$view.500'
  }
];
